# Generated by Django 4.2 on 2023-09-30 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_caption_alter_post_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.FileField(upload_to='posts/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png', 'mkv', 'mp4'])]),
        ),
    ]
