# Generated by Django 4.2 on 2023-09-30 13:23

import django.core.validators
from django.db import migrations, models
import post.validators


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_media_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.FileField(upload_to='posts/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png', 'mkv', 'mp4']), post.validators.file_size_validator]),
        ),
    ]
