# Generated by Django 4.2 on 2023-06-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_comment_text_alter_post_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(error_messages='Image field is required.', upload_to='posts/images/%Y/%m/%d'),
        ),
    ]
