# Generated by Django 4.2 on 2023-09-28 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='target_ct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='action',
            name='target_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
