# Generated by Django 4.2 on 2023-09-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, default=None, null=True, verbose_name=[('Male', 'Male'), ('Female', 'Female')]),
        ),
    ]
