# Generated by Django 4.2 on 2023-05-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_contact_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='followed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
