# Generated by Django 4.2 on 2023-04-26 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_avatar_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Incorrect phone number', regex='\\A(09)(0|1|2|3)[0-9]{7}\\d\\Z')]),
        ),
    ]
