# Generated by Django 4.2 on 2023-09-27 01:26

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[user.validators.username]),
        ),
    ]
